In [1]:
import numpy as np

In [4]:
a=np.array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

https://datascienceschool.net/view-notebook/35099ac4aea146c69cc4b3f50aec736f/

- all elements must be same data type
- can not change element size
- vector opertation

In [6]:
a[:]

array([1, 2, 3])

In [7]:
a[0:2]

array([1, 2])

In [8]:
a[0:1]

array([1])

In [9]:
a[0:]

array([1, 2, 3])

In [10]:
a[0]=3

In [11]:
a

array([3, 2, 3])

In [14]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [16]:
a=np.array(data)

In [17]:
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
data*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]