In [1]:
import numpy as np

In [4]:
a=np.array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

https://datascienceschool.net/view-notebook/35099ac4aea146c69cc4b3f50aec736f/

- all elements must be same data type
- can not change element size
- vector operation supported

In [6]:
a[:]

array([1, 2, 3])

In [7]:
a[0:2]

array([1, 2])

In [8]:
a[0:1]

array([1])

In [9]:
a[0:]

array([1, 2, 3])

In [10]:
a[0]=3

In [11]:
a

array([3, 2, 3])

In [14]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [16]:
a=np.array(data)

In [17]:
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
data*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
a<4

array([ True,  True,  True,  True, False, False, False, False, False, False], dtype=bool)

In [20]:
type(a<4)

numpy.ndarray

In [35]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])

In [36]:
len(d),len(d[0]),len(d[0][0])

(2, 3, 4)

In [37]:
d[0][0][3]

4

In [38]:
d.shape

(2, 3, 4)

In [40]:
d.ndim

3

In [43]:
d[0, 0, 0]

1

In [45]:
d[0, 0, 3]

4

In [46]:
d[0]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
d[0,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
d[:,1]

array([[ 5,  6,  7,  8],
       [15, 16, 17, 18]])

In [50]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

In [51]:
a[:,0]

array([0, 4])

In [52]:
a[0]

array([0, 1, 2, 3])

In [53]:
a[1, 1:]

array([5, 6, 7])

In [54]:
a[1, 1:-1]

array([5, 6])

In [55]:
a[1,-1]

7

In [56]:
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])

In [57]:
m.shape

(3, 5)

In [59]:
m[1,2]

7

In [60]:
m[-1,-1]

14

In [61]:
m[1:,2]

array([ 7, 12])

In [62]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

In [64]:
l=range(0,5)

In [65]:
type(l)

range

In [67]:
a=np.array(l)

In [68]:
a

array([0, 1, 2, 3, 4])

In [69]:
a[3]=8

In [70]:
a

array([0, 1, 2, 8, 4])

In [71]:
b=a

In [72]:
b[0]=1

In [73]:
a

array([1, 1, 2, 8, 4])

In [74]:
a[0]=0

In [77]:
a=np.array(range(0,10))

In [78]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
b=a % 2 == 0

In [82]:
b

array([ True, False,  True, False,  True, False,  True, False,  True, False], dtype=bool)

배열 인덱싱의 방식에은 불리안(Boolean) 배열 방식과 정수 배열 방식 두가지

In [81]:
a[b]

array([0, 2, 4, 6, 8])

In [90]:
c=np.array([1,1,1,2,2,2,3,3,3, 4,4,4])

In [91]:
a[1]=1111

In [92]:
a[c]

array([1111, 1111, 1111,    2,    2,    2,    3,    3,    3,    4,    4,
          4])

exercise

In [93]:
x=np.array(range(1,21))

In [94]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [95]:
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [96]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [102]:
x[(x%3==0) & (x%4 ==1)]

array([9])

In [104]:
x.dtype

dtype('int64')

In [105]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [106]:
x

array([ 1.,  2.,  3.], dtype=float32)

In [107]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

/Users/likebebop/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':
/Users/likebebop/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([  0.,  inf, -inf,  nan])

In [108]:
b = np.zeros((2, 3))
b
b.dtype

dtype('float64')

In [109]:
b

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [118]:
np.zeros((2, 3), dtype="U")

array([['', '', ''],
       ['', '', '']], 
      dtype='<U1')

In [119]:
np.linspace(0, 100, 5)

array([   0.,   25.,   50.,   75.,  100.])

In [120]:
A = np.array([[1, 2, 3], [4, 5, 6]])

In [121]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [122]:
A.T.shape

(3, 2)

In [124]:
A.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6]])

In [125]:
A.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [126]:
A.flatten()

array([1, 2, 3, 4, 5, 6])

In [127]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
B=A.flatten()

In [129]:
B[0]=7

In [130]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
B

array([7, 2, 3, 4, 5, 6])

In [132]:
A.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [133]:
B=A.reshape(3,-1)

In [134]:
B[0]=3

In [135]:
A

array([[3, 3, 3],
       [4, 5, 6]])

In [136]:
B

array([[3, 3],
       [3, 4],
       [5, 6]])

In [137]:
A[0]=1

In [138]:
B

array([[1, 1],
       [1, 4],
       [5, 6]])

In [139]:
A

array([[1, 1, 1],
       [4, 5, 6]])

In [140]:
A[0,0]=3

In [141]:
B

array([[3, 1],
       [1, 4],
       [5, 6]])

In [142]:
A

array([[3, 1, 1],
       [4, 5, 6]])

In [143]:
A[0]=2

In [144]:
A

array([[2, 2, 2],
       [4, 5, 6]])

In [145]:
B

array([[2, 2],
       [2, 4],
       [5, 6]])

In [147]:
import copy
B=copy.copy(A)

In [148]:
B

array([[2, 2, 2],
       [4, 5, 6]])

In [149]:
A[0]=1

In [150]:
B

array([[2, 2, 2],
       [4, 5, 6]])

In [151]:
A

array([[1, 1, 1],
       [4, 5, 6]])